language: node_js
node_js:
- '5.1'
notifications:
  slack:
    secure: pZ5LBxdOunYr2yki24BE4dP0BpPUrEXV6RqsnwwANwa2jOksrm5ftpwR1x7oFDHUFO00J8l1fqF3gQjK16FuOLCHaNUbk/K+AyqF06oH5TU0RA6Qz3vpDZ2ZosGCTAKpE8ycinuZLBwadzheluSMpBl11EbbEd4fzqwz8/pMt+CgqZ575J3+jl3uhLWl4/HJFrIrYgrbPV5pj054lTmkkpDjObhQWa3i+HJGkplolPirlw/CMSiZIXmfxOUlUGdknuj4pKTq7hxhioOPMe1qUFK74t6LO6QyB5xBb+3uAsI7CyivJ+vEVc+raFEoewCZck8TglyAPcozirdTQtryQeZiatNwcJMnV0BW5O20I2Ts71Hwo/s5eQUl2T1bAmcP4GKjqWLQZ3LtcaAxJsg6vlTxmt/HjIDn38B+sox2usZbSw2r40oiwbVdocZ6Ug4lNCtfuf8znPyCa6HkhvCFHvER1u5ElbRTCF1E57eonYSLZtzBta50ArHlD7UW2BRQfQ5lsg4v2ek+hshBmlGiqqDc97KMTBMv9NWyJlUWOjQUiJY5a/rI6NFpB3P3gWTA/GhXNvEIw7r4zlggRndqC90vjXHkCExnWg/1uZW9yu3FYGZqEjjWN1vwUYBomQMQt2KV2X/4N3kKn0jUS0xlFQm9MG1CDp/e/GNAc3Ey30k=
  on_success: never
  on_failure: always
  on_start: never
